#!/bin/bash

mkdir -p ~/Desktop/pdfs

while IFS= read -d $'\0' -r file ; do
	echo -n "Processing: $file -"
	enscript -p "${file}.ps" $file
	ps2pdf "${file}.ps" "${file}.pdf"
	rm "${file}.ps"
	mv "${file}.pdf" ~/Desktop/pdfs
done < <(find . -type f \( ! -iname ".*" ! -iname "*.swp" ! -iname "*.ps" \) -print0)
